[package]
name = "ProjectA_UniverseEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-channel = "1"
ratatui = "0.30.0-beta.0"
crossterm = "0.29.0"